language: node_js
node_js:
    - "8.10.0"

services:
    - mysql

before_install:
    - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS `zniszcz-auth-test`;'
    - cp ./config/config.json.dist ./config/config.json
    - cp ./config/crypto.json.dist ./config/crypto.json

install:
    - npm install

before_script:
    - npm run sequelize db:migrate:undo:all
    - npm run sequelize db:migrate
    - npm run lint

script:
    - npm test

