language: node_js
node_js:
    - "8.10.0"

services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE zniszcz-auth-test;'
    - cp ./config/config.json.dist ./config/config.json
    - cp ./config/crypto.json.dist ./config/crypto.json
